- name: install common packages
  apt: pkg={{ item }} state=present
  with_items:
   - python-pip
   - python-dev
   - python-cairo
   - build-essential

- name: install django
  pip: name=django version=1.5
