---

# download timeout, change to local file copy
- name: download grafana
  get_url: url=http://grafanarel.s3.amazonaws.com/grafana-1.8.0-rc1.tar.gz dest=/opt/grafana.tar.gz

# - name: copy grafana.tar.gz to remote
#   copy: src=grafana-1.8.0-rc1.tar.gz dest=/opt/grafana.tar.gz

- name: extract archive
  command: chdir=/opt /bin/tar xvf /opt/grafana.tar.gz

- name: rename folder
  command: chdir=/opt mv grafana-1.8.0-rc1/ grafana

- name: remove tar.gz
  command: chdir=/opt rm grafana.tar.gz

- name: copy config
  template: src=config.js dest=/opt/grafana/config.js

- name: change owner
  file: path=/opt/grafana owner=www-data group=www-data recurse=yes
